language: java

jdk:
  - oraclejdk8

sudo: false

script:
  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy

before_install:
 - chmod +x gradlew

after_success:
- ./gradlew jacocoTestReport coveralls
