language: java

jdk:
  - oraclejdk8

sudo: false

script:
  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls
 - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
